export const repeatLabels = {
  none: "无",
  daily: "每天",
  weekly: "每周",
  monthly: "每月",
  yearly: "每年",
};

export const timedReminderOffsetLabels = {
  none: "无",
  "on-time": "准时",
  "before-5m": "提前5分钟",
  "before-30m": "提前30分钟",
  "before-1h": "提前1小时",
  "before-1d": "提前1天",
  custom: "自定义",
};

export const allDayReminderOffsetLabels = {
  none: "无",
  "same-day": "当天",
  "before-1d": "提前1天",
  "before-2d": "提前2天",
  "before-3d": "提前3天",
  "before-1w": "提前1周",
  custom: "自定义",
};

export const customOffsetUnitLabels = {
  minutes: "分钟",
  hours: "小时",
  days: "天",
  weeks: "周",
};

export const icons = {
  home: '<svg class="icon" viewBox="0 0 24 24"><path d="m3 11 9-8 9 8"/><path d="M5 10v10h14V10"/><path d="M9 20v-6h6v6"/></svg>',
  scan: '<svg class="icon" viewBox="0 0 24 24"><path d="M7 3H5a2 2 0 0 0-2 2v2"/><path d="M17 3h2a2 2 0 0 1 2 2v2"/><path d="M21 17v2a2 2 0 0 1-2 2h-2"/><path d="M7 21H5a2 2 0 0 1-2-2v-2"/><path d="M7 12h10"/></svg>',
  search: '<svg class="icon" viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m21 21-4.3-4.3"/></svg>',
  bell: '<svg class="icon" viewBox="0 0 24 24"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M13.7 21a2 2 0 0 1-3.4 0"/></svg>',
  map: '<svg class="icon" viewBox="0 0 24 24"><path d="M9 18 3 21V6l6-3 6 3 6-3v15l-6 3-6-3Z"/><path d="M9 3v15"/><path d="M15 6v15"/></svg>',
  plus: '<svg class="icon" viewBox="0 0 24 24"><path d="M12 5v14"/><path d="M5 12h14"/></svg>',
  camera: '<svg class="icon" viewBox="0 0 24 24"><path d="M14.5 4h-5L7 7H4a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-3l-2.5-3Z"/><circle cx="12" cy="13" r="3"/></svg>',
  check: '<svg class="icon" viewBox="0 0 24 24"><path d="m20 6-11 11-5-5"/></svg>',
  rotate: '<svg class="icon" viewBox="0 0 24 24"><path d="M3 12a9 9 0 1 0 3-6.7"/><path d="M3 3v6h6"/></svg>',
  box: '<svg class="icon" viewBox="0 0 24 24"><path d="m21 8-9-5-9 5 9 5 9-5Z"/><path d="M3 8v8l9 5 9-5V8"/><path d="M12 13v8"/></svg>',
  spark: '<svg class="icon" viewBox="0 0 24 24"><path d="M13 2 9 14l-7 2 7 2 4 4 2-7 7-4-7-2-2-7Z"/></svg>',
  trash: '<svg class="icon" viewBox="0 0 24 24"><path d="M3 6h18"/><path d="M8 6V4h8v2"/><path d="M19 6l-1 14H6L5 6"/><path d="M10 11v5"/><path d="M14 11v5"/></svg>',
};

export const categoryLabels = {
  food: "食品",
  medicine: "药品",
  pet: "宠物",
  document: "证件",
  tool: "工具",
  daily: "日用",
  appliance: "家电",
};

export function createVisionConfig(platform = {}) {
  return {
  appVersion: "20260523-owlvit-first",
  assetVersion: "20260519-grounded-sam",
  remoteTransformersModule: "https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.7.2",
  allowRemoteVisionAssets: !platform.isNative,
  localTransformersModule: "/vendor/transformers/transformers.min.js",
  localHeicConverterScript: "/vendor/heic2any/heic2any.min.js",
  localManifest: "/vendor/vision-manifest.json",
  localModelPath: "/vendor/models/",
  catalogIndex: "/data/vision-index.seed.json",
  groundingDinoModel: "onnx-community/grounding-dino-tiny-ONNX",
  detectionModel: "Xenova/owlvit-base-patch32",
  preferredDetector: "owlvit",
  enableGroundingDinoFallback: false,
  samModel: "Xenova/slimsam-77-uniform",
  catalogModel: "Xenova/clip-vit-base-patch32",
  detectionThreshold: 0.05,
  groundingThreshold: 0.08,
  detectionNameThreshold: 0.11,
  catalogThreshold: 0.26,
  maxDetectedObjects: 28,
  maxUploadDimension: 1600,
  detectionMaxDimension: 1280,
  maxUploadDataUrlLength: 850000,
  uploadJpegQuality: 0.82,
  uploadDecodeTimeoutMs: 18000,
  heicConversionTimeoutMs: 45000,
  maxSamRefinements: 0,
  samMinBoxArea: 0.42,
  groundingPromptBatchSize: 48,
  owlVitPromptBatchSize: 48,
  owlVitLabelLimit: 48,
  maxWasmThreads: 4,
  recognitionCacheSize: 6,
  candidateCropVersion: "crop-640-v2",
  candidateCropMaxDimension: 640,
  candidateCropQuality: 0.9,
  cloudRecognitionEndpoint: "",
  };
}

export const unknownObjectNames = ["物品A", "物品B", "物品C", "物品D", "物品E", "物品F", "物品G", "物品H", "物品I", "物品J", "物品K", "物品L"];

export const visionCatalog = [
  {
    id: "television",
    name: "电视",
    category: "appliance",
    labels: ["television", "tv", "flat screen tv", "black television screen"],
    prompts: ["television", "flat screen tv"],
    searchQueries: ["flat screen tv"],
  },
  {
    id: "pendant-light",
    name: "吊灯",
    category: "daily",
    labels: ["pendant light", "ceiling lamp", "hanging light"],
    prompts: ["pendant light", "ceiling lamp"],
    searchQueries: ["pendant light"],
  },
  {
    id: "wall-ornament",
    name: "挂饰",
    category: "daily",
    labels: ["wall ornament", "hanging decoration", "wall decoration"],
    prompts: ["wall ornament", "hanging decoration"],
    searchQueries: ["wall ornament"],
  },
  {
    id: "speaker",
    name: "音响",
    category: "appliance",
    labels: ["speaker", "audio speaker", "bookshelf speaker", "floor standing speaker", "floor speaker", "left speaker", "right speaker", "speaker with orange grille"],
    prompts: ["speaker", "audio speaker", "bookshelf speaker", "floor speaker"],
    searchQueries: ["bookshelf speaker", "home audio speaker"],
  },
  {
    id: "speaker-grille",
    name: "音箱面罩",
    category: "appliance",
    labels: ["speaker grille", "speaker cover", "orange speaker grille"],
    prompts: ["speaker grille", "speaker cover"],
    searchQueries: ["speaker grille"],
  },
  {
    id: "amplifier",
    name: "功放",
    category: "appliance",
    labels: ["amplifier", "audio amplifier", "stereo receiver", "stereo amplifier", "silver amplifier", "silver stereo receiver", "audio receiver"],
    prompts: ["amplifier", "audio amplifier", "stereo receiver", "silver amplifier"],
    searchQueries: ["stereo amplifier", "audio receiver"],
  },
  {
    id: "turntable",
    name: "唱片机",
    category: "appliance",
    labels: ["turntable", "record player", "black turntable", "record player on shelf"],
    prompts: ["turntable", "record player", "black turntable"],
    searchQueries: ["turntable record player"],
  },
  {
    id: "remote-control",
    name: "遥控器",
    category: "tool",
    labels: ["remote control", "tv remote", "black remote control", "small black remote", "remote control on shelf"],
    prompts: ["remote control", "tv remote", "small black remote"],
    searchQueries: ["tv remote control"],
  },
  {
    id: "media-player",
    name: "播放器",
    category: "appliance",
    labels: ["media player", "audio player", "dvd player", "black media player", "black electronic device", "audio component"],
    prompts: ["media player", "audio player", "dvd player", "black electronic device"],
    searchQueries: ["media player", "audio player"],
  },
  {
    id: "tv-cabinet",
    name: "电视柜",
    category: "daily",
    labels: ["tv cabinet", "television cabinet", "white tv stand", "media cabinet", "media console", "tv console", "entertainment center", "drawer under tv", "cabinet drawer front"],
    prompts: ["tv cabinet", "television cabinet", "media console", "tv console"],
    searchQueries: ["tv cabinet"],
  },
  {
    id: "cabinet",
    name: "柜子",
    category: "daily",
    labels: ["cabinet", "storage cabinet", "cupboard", "side cabinet", "wooden cabinet"],
    prompts: ["cabinet", "storage cabinet", "cupboard"],
    searchQueries: ["storage cabinet", "cupboard"],
  },
  {
    id: "drawer",
    name: "抽屉",
    category: "daily",
    labels: ["drawer", "open drawer", "drawer front", "cabinet drawer", "dresser drawer"],
    prompts: ["drawer", "cabinet drawer"],
    searchQueries: ["cabinet drawer", "drawer"],
  },
  {
    id: "cabinet-door",
    name: "柜门",
    category: "daily",
    labels: ["cabinet door", "cupboard door", "storage door", "drawer handle"],
    prompts: ["cabinet door", "cupboard door"],
    searchQueries: ["cabinet door"],
  },
  {
    id: "storage-compartment",
    name: "储物格",
    category: "daily",
    labels: ["storage compartment", "shelf compartment", "cubby", "cabinet compartment", "open shelf"],
    prompts: ["storage compartment", "shelf compartment"],
    searchQueries: ["storage compartment"],
  },
  {
    id: "small-speaker",
    name: "小音箱",
    category: "appliance",
    labels: ["small speaker", "mini speaker", "small audio speaker"],
    prompts: ["small speaker", "mini speaker"],
    searchQueries: ["small speaker"],
  },
  {
    id: "small-device",
    name: "小设备",
    category: "appliance",
    labels: ["small device", "small electronic device", "black device"],
    prompts: ["small electronic device", "black device"],
    searchQueries: ["small electronic device"],
  },
  {
    id: "pillow",
    name: "抱枕",
    category: "daily",
    labels: ["pillow", "cushion", "throw pillow"],
    prompts: ["pillow", "cushion"],
    searchQueries: ["throw pillow"],
  },
  {
    id: "air-conditioner",
    name: "空调",
    category: "appliance",
    labels: ["air conditioner", "floor air conditioner", "standing air conditioner"],
    prompts: ["air conditioner", "floor air conditioner"],
    searchQueries: ["floor air conditioner"],
  },
  {
    id: "data-cable",
    name: "数据线",
    category: "tool",
    labels: ["cable", "usb cable", "charging cable"],
    prompts: ["usb cable", "charging cable"],
    searchQueries: ["usb cable", "type c cable"],
  },
  {
    id: "charger",
    name: "充电器",
    category: "tool",
    labels: ["charger", "power adapter", "phone charger"],
    prompts: ["charger", "power adapter", "phone charger"],
    searchQueries: ["phone charger", "usb power adapter"],
  },
  {
    id: "battery",
    name: "电池",
    category: "tool",
    labels: ["battery", "aa battery", "aaa battery"],
    prompts: ["battery", "aa battery", "aaa battery"],
    searchQueries: ["aa battery", "aaa battery"],
  },
  {
    id: "medicine-box",
    name: "药盒",
    category: "medicine",
    labels: ["medicine box", "pill box", "pill bottle"],
    prompts: ["medicine box", "pill box", "pill bottle"],
    searchQueries: ["medicine box", "pill bottle"],
  },
  {
    id: "storage-box",
    name: "收纳盒",
    category: "daily",
    labels: ["storage box", "storage basket", "plastic bin"],
    prompts: ["storage box", "storage basket", "plastic bin"],
    searchQueries: ["storage box", "plastic storage bin"],
  },
  {
    id: "key",
    name: "钥匙",
    category: "tool",
    labels: ["key", "keys", "keychain"],
    prompts: ["key", "keys", "keychain"],
    searchQueries: ["house keys", "keychain"],
  },
];

export const genericDetectionLabels = [
  { label: "window", name: "窗户", category: "daily" },
  { label: "curtain", name: "窗帘", category: "daily" },
  { label: "television cabinet drawer", name: "抽屉", category: "daily" },
  { label: "tv stand drawer", name: "抽屉", category: "daily" },
  { label: "tv console drawer", name: "抽屉", category: "daily" },
  { label: "media cabinet drawer", name: "抽屉", category: "daily" },
  { label: "white drawer front", name: "抽屉", category: "daily" },
  { label: "horizontal drawer", name: "抽屉", category: "daily" },
  { label: "cabinet drawer handle", name: "抽屉", category: "daily" },
  { label: "cabinet handle", name: "柜门", category: "daily" },
  { label: "cabinet shelf", name: "储物格", category: "daily" },
  { label: "shelf under television", name: "架子", category: "daily" },
  { label: "cabinet", name: "柜子", category: "daily" },
  { label: "storage cabinet", name: "柜子", category: "daily" },
  { label: "cupboard", name: "柜子", category: "daily" },
  { label: "drawer", name: "抽屉", category: "daily" },
  { label: "drawer front", name: "抽屉", category: "daily" },
  { label: "cabinet drawer", name: "抽屉", category: "daily" },
  { label: "cabinet door", name: "柜门", category: "daily" },
  { label: "shelf", name: "架子", category: "daily" },
  { label: "storage compartment", name: "储物格", category: "daily" },
  { label: "shelf compartment", name: "储物格", category: "daily" },
  { label: "cable", name: "线材", category: "tool" },
  { label: "black cable", name: "线材", category: "tool" },
  { label: "food package", name: "食品包装", category: "food" },
  { label: "bottle", name: "瓶装物", category: "daily" },
  { label: "spray bottle", name: "喷雾瓶", category: "daily" },
  { label: "detergent bottle", name: "清洁液", category: "daily" },
  { label: "filter cartridge", name: "滤芯", category: "appliance" },
  { label: "pet supplies", name: "宠物用品", category: "pet" },
  { label: "bag", name: "袋装物", category: "daily" },
  { label: "document", name: "文件", category: "document" },
  { label: "book", name: "书本", category: "daily" },
  { label: "cup", name: "杯子", category: "daily" },
  { label: "bowl", name: "碗", category: "daily" },
  { label: "box", name: "盒状物", category: "daily" },
];

export const furnitureByRoom = {
  kitchen: [
    { x: 4, y: 8, w: 26, h: 68, cls: "slim" },
    { x: 34, y: 18, w: 25, h: 48, cls: "" },
    { x: 65, y: 12, w: 27, h: 62, cls: "slim" },
    { x: 22, y: 78, w: 54, h: 10, cls: "" },
  ],
  living: [
    { x: 9, y: 42, w: 32, h: 22, cls: "" },
    { x: 46, y: 50, w: 42, h: 24, cls: "" },
    { x: 12, y: 76, w: 70, h: 8, cls: "slim" },
  ],
  balcony: [
    { x: 6, y: 16, w: 26, h: 66, cls: "slim" },
    { x: 38, y: 52, w: 24, h: 20, cls: "" },
    { x: 68, y: 22, w: 20, h: 54, cls: "slim" },
  ],
  bedroom: [
    { x: 6, y: 13, w: 31, h: 67, cls: "slim" },
    { x: 43, y: 46, w: 42, h: 24, cls: "" },
    { x: 56, y: 20, w: 18, h: 18, cls: "" },
  ],
};
