export const seedState = {
  activeTab: "capture",
  activeRoomId: "living",
  activePlaceId: null,
  query: "",
  lastAnswer: null,
  capture: {
    roomId: "living",
    placeId: null,
    image: null,
    imageRef: null,
    candidates: [],
    activeCandidateId: null,
    recognitionStatus: "idle",
    recognitionError: "",
    recognitionDiagnostics: null,
    preprocessingMs: null,
    imageMeta: null,
    provider: "none",
  },
  namingFeedback: [],
  cameraOn: false,
  rooms: [
    { id: "living", name: "客厅", type: "living", places: [] },
    { id: "kitchen", name: "厨房", type: "kitchen", places: [] },
    { id: "balcony", name: "阳台", type: "balcony", places: [] },
    { id: "bedroom", name: "卧室", type: "bedroom", places: [] },
  ],
  items: [],
};
